services:
  monitor:
    image: apwide/k8s-golive-agent:1.0.9
    network_mode: host
    entrypoint: "/k8s-golive-agent --kubeconfig=/etc/kube/config --goliveconfig=/etc/golive/config-template.yaml -v=2"
    volumes:
      - ./config:/etc/golive
      - ~/.kube/config:/etc/kube/config
